import re
import json

with open('app.jsx', 'r', encoding='utf-8') as f:
    content = f.read()

# Find the defaultProducts array
match = re.search(r'const defaultProducts = \[(.*?)\];', content, re.DOTALL)
if not match:
    print("Could not find defaultProducts")
    exit(1)

products_block = match.group(1)

# Let's clean up and parse
# Since it's JS literal, we can convert it to JSON-like by substituting names to double quotes
# But wait, it's easier to find each product with a regex
product_matches = re.findall(r'\{\s*id:\s*(\d+),\s*name:\s*"(.*?)",\s*price:\s*(\d+),\s*category:\s*"(.*?)",\s*image:\s*"(.*?)",\s*desc:\s*"(.*?)",\s*stock:\s*(\d+),\s*sold:\s*(\d+)\s*\}', products_block, re.DOTALL)

print(f"Found {len(product_matches)} products.")

sql_inserts = []
for p in product_matches:
    p_id, name, price, category, image, desc, stock, sold = p
    # Clean up single quotes for SQL
    name_esc = name.replace("'", "''")
    desc_esc = desc.replace("'", "''")
    image_esc = image.replace("'", "''")
    category_esc = category.replace("'", "''")
    
    sql = f"({p_id}, '{name_esc}', {price}, '{category_esc}', '{image_esc}', '{desc_esc}', {stock}, {sold})"
    sql_inserts.append(sql)

joined_sql = ",\n".join(sql_inserts)
full_sql = f"""
-- Create Table products
CREATE TABLE IF NOT EXISTS public.products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone default now(),
    name text not null,
    price bigint not null,
    stock integer not null default 0,
    sold integer not null default 0,
    image_url text,
    category_id text,
    "desc" text
);

-- Enable Row Level Security (optional, or disable if public access)
-- ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- If RLS is enabled, uncomment these to allow anonymous reads and admin modifications
-- CREATE POLICY "Allow public read-only access" ON public.products FOR SELECT USING (true);
-- CREATE POLICY "Allow all access for authenticated users" ON public.products FOR ALL TO authenticated USING (true);

-- Clear existing products to prevent duplicates
TRUNCATE public.products RESTART IDENTITY CASCADE;

-- Insert Seed Products (20 Items)
INSERT INTO public.products (id, name, price, category_id, image_url, "desc", stock, sold)
VALUES
{joined_sql};
"""

with open('seed_products.sql', 'w', encoding='utf-8') as sf:
    sf.write(full_sql)

print("SQL script generated successfully in seed_products.sql")
