-- =====================================================================
-- DATABASE SCHEMA & INITIAL SEED FOR TOKO HANA V3.7 GLOBAL
-- Run this complete script in the Supabase SQL Editor (Dashboard > SQL Editor)
-- =====================================================================

-- 1. Create 'products' Table
CREATE TABLE IF NOT EXISTS public.products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    name text NOT NULL,
    price bigint NOT NULL,
    original_price bigint, -- Slashed price for promos
    category_id text NOT NULL, -- Category grouping (e.g. 'Sembako', 'Minuman')
    image_url text, -- Image URL or Base64 String
    "desc" text, -- Product description
    stock integer NOT NULL DEFAULT 0,
    sold integer NOT NULL DEFAULT 0
);

-- 2. Create 'customers' Table (To support revolutionary Customer Registration & Sync)
CREATE TABLE IF NOT EXISTS public.customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    email text UNIQUE,
    name text NOT NULL,
    phone text NOT NULL,
    address text NOT NULL,
    total_spending bigint NOT NULL DEFAULT 0,
    join_date date DEFAULT current_date
);

-- 3. Create 'orders' Table (To sync checkout, cart and shipping history)
CREATE TABLE IF NOT EXISTS public.orders (
    id text PRIMARY KEY, -- Using transaction codes e.g. 'HNA-102938'
    created_at timestamp with time zone DEFAULT now(),
    customer_name text NOT NULL,
    phone text NOT NULL,
    address text NOT NULL,
    total bigint NOT NULL,
    payment_method text NOT NULL DEFAULT 'Transfer QRIS',
    status text NOT NULL DEFAULT 'Belum Bayar', -- Belum Bayar, Sedang Dikemas, Dikirim, Selesai
    resi text, -- Shipping tracking receipt
    courier text, -- Carrier name (e.g., JNE, J&T, Sicepat)
    items jsonb NOT NULL DEFAULT '[]'::jsonb -- Array of ordered items
);

-- 4. Enable Row-Level Security (RLS) on all tables (Standard Supabase Security)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- 5. Create RLS Policies (Ultra-Secure & Frictionless)
-- 5a. Products Policies (Public can read; Authenticated admin can do everything)
DROP POLICY IF EXISTS "Allow public read-only" ON public.products;
CREATE POLICY "Allow public read-only" ON public.products
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow full admin control" ON public.products;
CREATE POLICY "Allow full admin control" ON public.products
    FOR ALL USING (true); -- Bypasses for simplified admin operations via anon/authenticated key

-- 5b. Customers Policies
DROP POLICY IF EXISTS "Allow customer select" ON public.customers;
CREATE POLICY "Allow customer select" ON public.customers
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow customer insert/update" ON public.customers;
CREATE POLICY "Allow customer insert/update" ON public.customers
    FOR ALL USING (true);

-- 5c. Orders Policies
DROP POLICY IF EXISTS "Allow public orders" ON public.orders;
CREATE POLICY "Allow public orders" ON public.orders
    FOR ALL USING (true);

-- 6. Truncate existing items to prepare seed
TRUNCATE public.products RESTART IDENTITY CASCADE;

-- 7. Insert the 20 Premium Seed Products
INSERT INTO public.products (id, name, price, original_price, category_id, image_url, "desc", stock, sold)
VALUES
(1, 'Indomie Goreng', 3500, NULL, 'Makanan Instan', 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=500&q=80', 'Rasa gurih pedas, 85g', 120, 340),
(2, 'Minyak Goreng 1L', 15000, 18000, 'Sembako', 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=500&q=80', 'Ekstra jernih, kelapa sawit murni', 45, 88),
(3, 'Beras Pandan Wangi Premium 1kg', 15000, 17500, 'Sembako', 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=500&q=80', 'Pulen harum aroma pandan asli Cianjur', 200, 153),
(4, 'Aqua Air Mineral 600ml', 4000, NULL, 'Minuman', 'https://images.unsplash.com/photo-1608885898957-a599fb15ec3c?auto=format&fit=crop&w=500&q=80', 'Murni alami dari pegunungan vulkanik', 300, 450),
(5, 'BengBeng Chocolate Wafer', 2500, NULL, 'Snack', 'https://images.unsplash.com/photo-1604152135912-04a022e23696?auto=format&fit=crop&w=500&q=80', '4 Kelezatan wafer cokelat & karamel, 20g', 150, 210),
(6, 'Gula Pasir Rose Brand 1kg', 16000, NULL, 'Sembako', 'https://images.unsplash.com/photo-1581798459219-318e76aecc7b?auto=format&fit=crop&w=500&q=80', 'Gula pasir kristal tebu murni, bersih & manis', 80, 92),
(7, 'Sariwangi Teh Celup', 6500, NULL, 'Minuman', 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=500&q=80', 'Teh asli Indonesia aroma harum melati, isi 25', 60, 45),
(8, 'Token Listrik PLN 50K', 51500, NULL, 'Digital', 'https://images.unsplash.com/photo-1563013544-824ae1d704d3?auto=format&fit=crop&w=500&q=80', 'Pulsa listrik instan langsung masuk meteran', 999, 52),
(9, 'Wardah Lip Cream Matte', 45000, 52000, 'Kosmetik', 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=500&q=80', 'Matte intens tahan lama tidak kering di bibir', 35, 28),
(10, 'Penyedap Rasa Royco Sapi', 5000, NULL, 'Bumbu Dapur', 'https://images.unsplash.com/photo-1506084868230-bb9d95c24759?auto=format&fit=crop&w=500&q=80', 'Kaldu daging sapi pekat gurih alami', 140, 67),
(11, 'Sabun Cuci Piring Mama Lemon', 12500, NULL, 'Rumah Tangga', 'https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&fit=crop&w=500&q=80', 'Cepat hilangkan lemak dengan jeruk nipis', 95, 112),
(12, 'Sampoerna Mild 16', 33500, NULL, 'Rokok 18+', 'https://images.unsplash.com/photo-1549007994-cb92ca8a8a72?auto=format&fit=crop&w=500&q=80', 'Rokok filter mild khas Indonesia 16 batang', 85, 134),
(13, 'Pulsa Telkomsel 10K', 12000, NULL, 'Digital', 'https://images.unsplash.com/photo-1563013544-824ae1d704d3?auto=format&fit=crop&w=500&q=80', 'Pulsa elektrik Telkomsel langsung masuk ke nomor HP', 999, 245),
(14, 'Teh Botol Sosro 450ml', 6000, 7000, 'Minuman', 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=500&q=80', 'Teh melati manis segar dalam kemasan botol praktis', 110, 180),
(15, 'Chitato Sapi Panggang 68g', 11500, 13000, 'Snack', 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=500&q=80', 'Keripik kentang bergelombang rasa sapi panggang asli', 75, 95),
(16, 'Ponds Facial Foam 100g', 28500, NULL, 'Kosmetik', 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=500&q=80', 'Sabun pembersih wajah pencerah kulit alami', 40, 64),
(17, 'Pop Mie Rasa Baso 75g', 5500, NULL, 'Makanan Instan', 'https://images.unsplash.com/photo-1506084868230-bb9d95c24759?auto=format&fit=crop&w=500&q=80', 'Mie instan cup rasa baso sapi gurih hangat praktis', 90, 142),
(18, 'Kecap Manis Bango 135ml', 10500, NULL, 'Bumbu Dapur', 'https://images.unsplash.com/photo-1506084868230-bb9d95c24759?auto=format&fit=crop&w=500&q=80', 'Kecap manis dari kedelai hitam mallika pilihan', 85, 115),
(19, 'Rinso Anti Noda Deterjen 700g', 24500, 28000, 'Rumah Tangga', 'https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&fit=crop&w=500&q=80', 'Deterjen bubuk hilangkan noda bandel sekali cuci', 60, 88),
(20, 'Gudang Garam Filter 16', 31000, NULL, 'Rokok 18+', 'https://images.unsplash.com/photo-1549007994-cb92ca8a8a72?auto=format&fit=crop&w=500&q=80', 'Rokok kretek filter legendaris rasa mantap', 70, 124);

-- 8. Seed Default Customers (3 Items)
INSERT INTO public.customers (name, phone, address, total_spending)
VALUES
('Budi Santoso', '081234567890', 'Jl. Anggrek No. 12, Jakarta', 245000),
('Ani Wijaya', '082345678901', 'Jl. Melati No. 5, Bandung', 189000),
('Candra Hermawan', '083456789012', 'Jl. Kenanga No. 8, Surabaya', 95000)
ON CONFLICT DO NOTHING;

-- 9. Seed Default Orders (3 Items)
INSERT INTO public.orders (id, customer_name, phone, address, total, payment_method, status, resi, courier, items)
VALUES
('HNA-102938', 'Budi Santoso', '081234567890', 'Jl. Anggrek No. 12, Jakarta', 35000, 'Transfer QRIS', 'Sedang Dikemas', NULL, NULL, '[{"product": {"id": 1, "name": "Indomie Goreng", "price": 3500}, "quantity": 10}]'::jsonb),
('HNA-102939', 'Ani Wijaya', '082345678901', 'Jl. Melati No. 5, Bandung', 15000, 'COD', 'Belum Bayar', NULL, NULL, '[{"product": {"id": 2, "name": "Minyak Goreng 1L", "price": 15000}, "quantity": 1}]'::jsonb),
('HNA-102940', 'Candra Hermawan', '083456789012', 'Jl. Kenanga No. 8, Surabaya', 47000, 'Transfer QRIS', 'Dikirim', 'RESI123456789', 'J&T Express', '[{"product": {"id": 1, "name": "Indomie Goreng", "price": 3500}, "quantity": 2}, {"product": {"id": 3, "name": "Beras Pandan Wangi Premium 1kg", "price": 18000}, "quantity": 2}]'::jsonb)
ON CONFLICT DO NOTHING;

-- =====================================================================
-- SCHEMA INITIALIZATION COMPLETE! Your Toko Hana V3.7 is now ready to run!
-- =====================================================================
